# Generated by Django 5.0 on 2026-03-08 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='drivervehicleassignment',
            unique_together=set(),
        ),
    ]
