# Generated by Django 5.0 on 2026-03-08 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consumer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', 'Available'), ('on_trip', 'On Trip'), ('off_duty', 'Off Duty'), ('inactive', 'Inactive')], default='available', max_length=20)),
                ('total_trips_completed', models.IntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('efficiency_score', models.DecimalField(blank=True, decimal_places=2, help_text='ML-calculated efficiency metric', max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contractor', models.ForeignKey(help_text='Contractor managing this driver. For independent drivers, this equals user.', on_delete=django.db.models.deletion.CASCADE, related_name='managed_drivers', to=settings.AUTH_USER_MODEL)),
                ('current_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_driver', to='consumer.booking')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(choices=[('mini_truck', 'Mini Truck'), ('medium_truck', 'Medium Truck'), ('full_truck', 'Full Truck'), ('trailer', 'Trailer'), ('tempo', 'Tempo')], max_length=20)),
                ('capacity_weight', models.DecimalField(decimal_places=2, help_text='Payload capacity in tons', max_digits=10)),
                ('model_make', models.CharField(max_length=100)),
                ('fuel_type', models.CharField(choices=[('diesel', 'Diesel'), ('cng', 'CNG'), ('electric', 'Electric')], default='diesel', max_length=20)),
                ('length_feet', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('width_feet', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('height_feet', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('gps_device_id', models.CharField(blank=True, help_text='GPS tracker device ID', max_length=100)),
                ('current_location', models.CharField(blank=True, help_text='Last known city/region', max_length=200)),
                ('insurance_policy_number', models.CharField(blank=True, max_length=100)),
                ('insurance_expiry_date', models.DateField(blank=True, null=True)),
                ('puc_number', models.CharField(blank=True, help_text='Pollution certificate number', max_length=50)),
                ('puc_expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('in_use', 'In Use'), ('maintenance', 'Under Maintenance'), ('inactive', 'Inactive')], default='available', max_length=20)),
                ('total_trips_completed', models.IntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('odometer_reading', models.IntegerField(default=0, help_text='Current odometer reading in KM')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
                ('current_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_vehicle', to='consumer.booking')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DriverVehicleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_assignments', to='contractor.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_assignments', to='contractor.vehicle')),
            ],
            options={
                'ordering': ['-assigned_at'],
                'unique_together': {('driver', 'vehicle', 'is_active')},
            },
        ),
    ]
