# Generated by Django 5.0 on 2026-03-08 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('review', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('local', 'Local Shifting'), ('intercity', 'Intercity'), ('office', 'Office Relocation'), ('single_item', 'Single Item Delivery')], max_length=20)),
                ('pickup_address', models.TextField()),
                ('pickup_floor_number', models.IntegerField(blank=True, null=True)),
                ('pickup_lift_available', models.BooleanField(default=False)),
                ('pickup_parking_available', models.BooleanField(default=False)),
                ('drop_address', models.TextField()),
                ('drop_floor_number', models.IntegerField(blank=True, null=True)),
                ('drop_lift_available', models.BooleanField(default=False)),
                ('drop_parking_available', models.BooleanField(default=False)),
                ('cargo_type', models.CharField(choices=[('electronics', 'Electronics'), ('furniture', 'Furniture'), ('food', 'Food/Perishables'), ('construction', 'Construction Materials'), ('textiles', 'Textiles/Clothing'), ('general', 'General Cargo')], max_length=50)),
                ('cargo_weight', models.DecimalField(decimal_places=2, help_text='Estimated weight in KG', max_digits=10)),
                ('room_count', models.IntegerField(blank=True, help_text='Number of rooms', null=True)),
                ('packing_needed', models.BooleanField(default=False)),
                ('vehicle_type_preference', models.CharField(choices=[('mini_truck', 'Mini Truck'), ('medium_truck', 'Medium Truck'), ('full_truck', 'Full Truck'), ('trailer', 'Trailer'), ('tempo', 'Tempo')], max_length=20)),
                ('pickup_datetime', models.DateTimeField()),
                ('special_notes', models.TextField(blank=True)),
                ('ml_suggested_vehicle_type', models.CharField(blank=True, choices=[('mini_truck', 'Mini Truck'), ('medium_truck', 'Medium Truck'), ('full_truck', 'Full Truck'), ('trailer', 'Trailer'), ('tempo', 'Tempo')], max_length=20, null=True)),
                ('ml_suggested_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('driver_selected', 'Driver Selected'), ('payment_pending', 'Payment Pending'), ('confirmed', 'Confirmed'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('advance_percentage', models.DecimalField(decimal_places=2, default=20.0, help_text='Advance payment percentage', max_digits=5)),
                ('advance_paid', models.BooleanField(default=False)),
                ('advance_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('full_payment_paid', models.BooleanField(default=False)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('awaiting_acceptance', 'Awaiting Acceptance'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='awaiting_acceptance', max_length=30)),
                ('booking_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('trip_started_at', models.DateTimeField(blank=True, null=True)),
                ('trip_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
